char	*CONFIG_TLS_CONNECT = NULL;
char	*CONFIG_TLS_ACCEPT = NULL;
char	*CONFIG_TLS_CA_FILE = NULL;
char	*CONFIG_TLS_CRL_FILE = NULL;
char	*CONFIG_TLS_SERVER_CERT_ISSUER = NULL;
char	*CONFIG_TLS_SERVER_CERT_SUBJECT = NULL;
char	*CONFIG_TLS_CERT_FILE = NULL;
char	*CONFIG_TLS_KEY_FILE = NULL;
char	*CONFIG_TLS_PSK_IDENTITY = NULL;
char	*CONFIG_TLS_PSK_FILE = NULL;
char	*CONFIG_TLS_SERVER_CERT_FILE = NULL;
char	*CONFIG_ACTIVE_FORKS = NULL;
char	*CONFIG_PASSIVE_FORKS = NULL;
char	*CONFIT_TIMEUOT = NULL;

unsigned int	configured_tls_connect_mode;
unsigned int	configured_tls_accept_modes;
