#!/usr/bin/env bash

################################################################################
#
# Wrapper for test.pl.
#
################################################################################

set -o errexit
set -o nounset
set -o pipefail
#set -o xtrace

if [[ " $@ " == *" --help "* ]]; then
	cat << HELP_MESSAGE

WRAPPER CONFIGURATION

    To configure git, database and frontend, edit and fill all fields in test-wrapper.conf

WRAPPER USAGE

    First, you need to prepare Zabbix:
    $ ./test-wrapper --build-server --build-proxy

    Run a single test:
    $ TZ=UTC faketime '2021-01-23 00:00:00' ./test-wrapper --skip-build --test-case-file ../test-cases/sla-api/001-state-all-disabled.txt

    Run all tests in a directory:
    $ TZ=UTC faketime '2021-01-23 00:00:00' ./test-wrapper --skip-build --test-case-dir ../test-cases/sla-api

HELP_MESSAGE

	"$(dirname "$0")/test.pl" --help

	exit
fi

: ${CONF_FILE:="$(dirname $0)/test-wrapper.conf"}

if [[ -f "$CONF_FILE" ]]; then
	. "$CONF_FILE"
fi

: ${WORKSPACE:=$(pwd)}
: ${SOURCE_DIRECTORY:="$WORKSPACE/source"}
: ${SOURCE_DIRECTORY_TMP:="$SOURCE_DIRECTORY@tmp"}

export WORKSPACE

export GIT_URL=${GIT_URL:?"not specified"}
export GIT_BRANCH=${GIT_BRANCH:?"not specified"}

export ZBX_SERVER_DB_HOST=${ZBX_SERVER_DB_HOST:?"not specified"}
export ZBX_SERVER_DB_NAME=${ZBX_SERVER_DB_NAME:?"not specified"}
export ZBX_SERVER_DB_USER=${ZBX_SERVER_DB_USER:?"not specified"}
export ZBX_SERVER_DB_PASSWORD=${ZBX_SERVER_DB_PASSWORD?"not specified"} # may be an empty string

export ZBX_FRONTEND_URL=${ZBX_FRONTEND_URL:?"not specified"}
export ZBX_FRONTEND_USER=${ZBX_FRONTEND_USER:?"not specified"}
export ZBX_FRONTEND_PASSWORD=${ZBX_FRONTEND_PASSWORD:?"not specified"}

if [[ ! -d "$SOURCE_DIRECTORY_TMP" || "$(GIT_DIR="$SOURCE_DIRECTORY_TMP/.git" git rev-parse --abbrev-ref HEAD)" != "$GIT_BRANCH" ]]; then
	rm -rf "$SOURCE_DIRECTORY_TMP"
	git clone --depth 1 --branch "$GIT_BRANCH" "$GIT_URL" "$SOURCE_DIRECTORY_TMP"
fi

if [[ " $@ " != *" --skip-build "* ]]; then
	rm -rf "$SOURCE_DIRECTORY"
	cp -r "$SOURCE_DIRECTORY_TMP" "$SOURCE_DIRECTORY"
fi

sudo ln -sfn "$SOURCE_DIRECTORY/opt/zabbix" /opt/zabbix
"$(dirname "$0")/test.pl" "$@"
sudo unlink /opt/zabbix
