package ZabbixConstants;

use strict;
use warnings;

my %constants = (
	HOST_STATUS_MONITORED     => 0,
	HOST_STATUS_NOT_MONITORED => 1,
	HOST_STATUS_TEMPLATE      => 3,
	HOST_STATUS_PROXY_ACTIVE  => 5,
	HOST_STATUS_PROXY_PASSIVE => 6,

	HOST_ENCRYPTION_NONE        => 1,
	HOST_ENCRYPTION_PSK         => 2,
	HOST_ENCRYPTION_CERTIFICATE => 4,

	INTERFACE_TYPE_UNKNOWN => 0,
	INTERFACE_TYPE_AGENT   => 1,
	INTERFACE_TYPE_SNMP    => 2,
	INTERFACE_TYPE_IPMI    => 3,
	INTERFACE_TYPE_JMX     => 4,

	INTERFACE_USE_DNS => 0,
	INTERFACE_USE_IP  => 1,

	ITEM_TYPE_ZABBIX        => 0,
	ITEM_TYPE_TRAPPER       => 2,
	ITEM_TYPE_SIMPLE        => 3,
	ITEM_TYPE_INTERNAL      => 5,
	ITEM_TYPE_ZABBIX_ACTIVE => 7,
	ITEM_TYPE_AGGREGATE     => 8,
	ITEM_TYPE_HTTPTEST      => 9,
	ITEM_TYPE_EXTERNAL      => 10,
	ITEM_TYPE_DB_MONITOR    => 11,
	ITEM_TYPE_IPMI          => 12,
	ITEM_TYPE_SSH           => 13,
	ITEM_TYPE_TELNET        => 14,
	ITEM_TYPE_CALCULATED    => 15,
	ITEM_TYPE_JMX           => 16,
	ITEM_TYPE_SNMPTRAP      => 17,
	ITEM_TYPE_DEPENDENT     => 18,
	ITEM_TYPE_HTTPAGENT     => 19,
	ITEM_TYPE_SNMP          => 20,

	ITEM_STATUS_ACTIVE   => 0,
	ITEM_STATUS_DISABLED => 1,

	ITEM_VALUE_TYPE_FLOAT  => 0,
	ITEM_VALUE_TYPE_STR    => 1,
	ITEM_VALUE_TYPE_LOG    => 2,
	ITEM_VALUE_TYPE_UINT64 => 3,
	ITEM_VALUE_TYPE_TEXT   => 4,

	ZBX_PREPROC_MULTIPLIER           => 1,
	ZBX_PREPROC_RTRIM                => 2,
	ZBX_PREPROC_LTRIM                => 3,
	ZBX_PREPROC_TRIM                 => 4,
	ZBX_PREPROC_REGSUB               => 5,
	ZBX_PREPROC_BOOL2DEC             => 6,
	ZBX_PREPROC_OCT2DEC              => 7,
	ZBX_PREPROC_HEX2DEC              => 8,
	ZBX_PREPROC_DELTA_VALUE          => 9,
	ZBX_PREPROC_DELTA_SPEED          => 10,
	ZBX_PREPROC_XPATH                => 11,
	ZBX_PREPROC_JSONPATH             => 12,
	ZBX_PREPROC_VALIDATE_RANGE       => 13,
	ZBX_PREPROC_VALIDATE_REGEX       => 14,
	ZBX_PREPROC_VALIDATE_NOT_REGEX   => 15,
	ZBX_PREPROC_ERROR_FIELD_JSON     => 16,
	ZBX_PREPROC_ERROR_FIELD_XML      => 17,
	ZBX_PREPROC_ERROR_FIELD_REGEX    => 18,
	ZBX_PREPROC_THROTTLE_VALUE       => 19,
	ZBX_PREPROC_THROTTLE_TIMED_VALUE => 20,
	ZBX_PREPROC_SCRIPT               => 21,
	ZBX_PREPROC_PROMETHEUS_PATTERN   => 22,
	ZBX_PREPROC_PROMETHEUS_TO_JSON   => 23,
	ZBX_PREPROC_CSV_TO_JSON          => 24,
	ZBX_PREPROC_STR_REPLACE          => 25,

	ZBX_PREPROC_FAIL_DEFAULT       => 0,
	ZBX_PREPROC_FAIL_DISCARD_VALUE => 1,
	ZBX_PREPROC_FAIL_SET_VALUE     => 2,
	ZBX_PREPROC_FAIL_SET_ERROR     => 3,

	TRIGGER_STATUS_ENABLED  => 0,
	TRIGGER_STATUS_DISABLED => 1,

	TRIGGER_VALUE_FALSE => 0,
	TRIGGER_VALUE_TRUE  => 1,

	TRIGGER_SEVERITY_NOT_CLASSIFIED => 0,
	TRIGGER_SEVERITY_INFORMATION    => 1,
	TRIGGER_SEVERITY_WARNING        => 2,
	TRIGGER_SEVERITY_AVERAGE        => 3,
	TRIGGER_SEVERITY_HIGH           => 4,
	TRIGGER_SEVERITY_DISASTER       => 5,

	ZBX_RECOVERY_MODE_EXPRESSION          => 0,
	ZBX_RECOVERY_MODE_RECOVERY_EXPRESSION => 1,
	ZBX_RECOVERY_MODE_NONE                => 2,
);

use constant qw();
constant->import(\%constants);

use Exporter qw(import);
our @EXPORT = keys(%constants);

1;
