<?php

/*
	Usernames and passwords must be kept in sync with the frontends.

	Password hashes can be generated by executing:
	$ php -r 'echo password_hash($argv[1], PASSWORD_BCRYPT, ["cost" => 10]) . "\n";' -- '<password>'
*/

return [
	'users' => [
		'readonly' => [
			'username' => 'provisioning-api-readonly',
			'password' => '$2y$10$nD9fJYeWFsktv7wOMcg52Ob0LRgwrj4JWevPpemErLUo78FDp7WXK',
		],
		'readwrite' => [
			'username' => 'provisioning-api-readwrite',
			'password' => '$2y$10$nD9fJYeWFsktv7wOMcg52Ob0LRgwrj4JWevPpemErLUo78FDp7WXK',
		],
	],
	'databases' => [
		1 => [
			'host'       => 'localhost',
			'port'       => null,
			'database'   => 'rsm_server',
			'user'       => 'zabbix',
			'password'   => 'password',
			'ssl_key'    => null,
			'ssl_cert'   => null,
			'ssl_ca'     => null,
			'ssl_capath' => null,
			'ssl_cipher' => null,
		],
	],
	'frontends' => [
		1 => [
			'url' => 'http://127.0.0.1/icann-git/dev-papi/ui',
		],
	],
	'settings' => [
		'curl_timeout'           => 3,
		'max_tlds'               => 10,
		'max_registrars'         => 10,
		'max_probes'             => 10,
		'prettify_output_list'   => false,
		'prettify_output_object' => true,
	],
];
